### ISSUE TITLE
Failed to restore npm packages

### ISSUE THREAD

**Issue by jesusvalenzuelar** [RafaelSalguero/AngularTypescriptSkeleton#1]
Hi, I tried to restore nmp packages with:

`npm i`

but i have this error:

`npm ats@1.0.0 No repository field..`

**Comment by jesusvalenzuelar** [comment]
autoreq doesn't append "\" only "\" in your imports in the requireme.ts files.

**Comment by RafaelSalguero** [comment]
I will try to generate forward slashes instead of backslashes and see if that works, and set the repository field on the packages.json. Thanks
